import fs from 'node:fs';import assert from 'node:assert/strict';import ts from 'typescript';
const code=ts.transpileModule(fs.readFileSync('src/cellPuzzle.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {CellPuzzle}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const s=new CellPuzzle();
s.act('rope','take');s.act('rope','cut');assert.equal(s.has('rope'),false);
s.act('grog','take');assert.equal(s.has('grog'),false);
s.act('handle','take');assert.equal(s.has('jaw'),false);
assert.ok(!s.act('handle','examine').includes('mandibola'));
s.act('jug','extract');assert.equal(s.has('eye'),false);
s.act('jug','take');s.act('jug','extract');s.act('jug','extract');s.act('cup','take');s.act('cup','take');
assert.deepEqual(s.inventory,['jug','eye','cup']);assert.equal(s.visible('jug'),false);assert.equal(s.visible('cup'),false);
s.act('cabinet','interact');assert.equal(s.visible('grog'),true);s.act('grog','take');s.act('grog','break');assert.equal(s.has('grog'),true);
s.act('rope','interact','grog');assert.equal(s.has('grog'),true,'wrong combination preserves item');
s.act('handle','interact','grog');assert.equal(s.has('grog'),false);assert.equal(s.has('bottle'),true);
s.act('handle','take');assert.equal(s.has('jaw'),true);assert.equal(s.jawKnown,false);
s.act('skull','talk');assert.equal(s.jawKnown,true);assert.match(s.act('handle','examine'),/mandibola/);
s.act('skull','interact','jaw');assert.equal(s.jawGiven,true);assert.equal(s.has('jaw'),false);
s.act('bottle','break');assert.equal(s.has('broken'),true);s.act('broken','extract');assert.equal(s.has('shard'),true);assert.equal(s.has('broken'),false);
s.act('rope','interact','shard');s.act('rope','cut');assert.equal(s.inventory.filter(i=>i==='rope').length,1);assert.equal(s.ropeCut,true);
assert.equal(s.has('shard'),true);assert.equal(s.has('jug'),true);assert.equal(s.has('eye'),true);
console.log('PASS: complete cell puzzle, prerequisites, no duplicates, hidden jaw identity, non-destructive wrong combinations.');
